Feature/univar polynomial commit
NOOMA-42/pylookup pull request #4
Opened 2024-02-03 02:07 UTC by NOOMA-42

based on baloo univariate sumcheck.

2024-02-23 08:45 UTC, luckyyang requested changes

2024-02-23 08:45 UTC, luckyyang commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x / x
The computation for `Q2_x, XR_x` seems not right, you could refer to my code at line `#271`  in file https://github.com/NOOMA-42/pylookup/pull/5/files#diff-6458f24a7ddd0cfb4aa1bf4a9c04854b086c40e2ed309c341d968f6ebba3051dR271

2024-02-23 08:45 UTC, luckyyang commented on src/common_util/poly.py
> +    def div_with_remainder(self, other):
This method shouldn't be used, all polynomial division we used should not have reminder

2024-02-23 08:45 UTC, luckyyang commented on src/common_util/univariatesumcheck.py
> +        [2, 1, 2]
Should be [1, 0, 1]?

2024-02-23 08:45 UTC, luckyyang commented on src/common_util/univariatesumcheck_test.py
> +        H = left_rotate_root_of_unity(H)
Do not have to rotate, you can just use 1 as the first item of SRS: 1, w, w^2...

2024-02-23 15:03 UTC, NOOMA-42 commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x / x
If we treat D_x * t_x as dividend and z_I as divisor, isn't XR_X the residue?
<img width="915" alt="截圖 2024-02-23 下午11 01 31" src="https://github.com/NOOMA-42/pylookup/assets/35304302/e125d8ec-9fb5-4a68-ab39-85bfcff154c5">

ref: P.16

2024-02-23 15:08 UTC, NOOMA-42 commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x / x
ah I see, you minus residue first?

2024-02-23 15:47 UTC, luckyyang commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x / x
No, XR_X is not the residue. You can only calculate with this way: XR_X = Σ_i(a_i * b_i * normalized_lag_poly(root)) - Σ_i(a_i * b_i)

2024-02-23 15:49 UTC, luckyyang commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x / x
If we get residue/remainder, then there must be something wrong with our polynomial construction

2024-02-24 00:59 UTC, luckyyang commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x / x
Will change my code with this way

2024-03-03 16:28 UTC, NOOMA-42 commented on src/common_util/univariatesumcheck.py
> +    R_x = XR_x
Why can we skip division?

2024-03-03 16:29 UTC, NOOMA-42 commented on src/common_util/univariatesumcheck_test.py
> +        table = [1, 2, 3, 4]
I'm not sure I understand this

2024-05-19 14:43 UTC, closed without merging